AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for innovator-island-ts
Globals:
  Function:
    Timeout: 6
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  FATcontroller:
    Type: AWS::SNS::Topic
  DDBtable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  UpdateRidesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: packages/fat-controller/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Environment:
        Variables:
          DDBtable: !Ref DDBtable
          TopicArn: !Ref FATcontroller
      Events:
        UpdateRidesEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/app.ts
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true
Outputs:
  RideUpdatesSNStopic:
    Description: SNS topic to receive ride uptime updates
    Value: !Ref FATcontroller
